### ISSUE TITLE
Question regarding Python functions

### ISSUE THREAD

**Issue by vivien000** [eth-sri/lmql#12]
Congratulations on this exciting release! I have some questions regarding the Python functions that can be called from the LMQL query. In the paper, you mention that such functions are assumed to be pure and deterministic.

Is it enforced by `lmql`, i.e. does `lmql` take charge of caching these function calls? Or is this left to the user?

I'm asking because it could be useful to call non-deterministic functions or functions with side effects so ideally it would be possible to not cache some function calls.

**Comment by lbeurerkellner** [comment]
Hi Vivien,

LMQL does not enforce purity or caching, as it is relatively simple to implement on the user side, and not always what you may want. To illustrate, it may help to know where this constraint: When running with a branching decoder, like beam search, your prompt program will be executed multiple times, for the different hypotheses that are being decoded. In these cases, having global state and side effects would lead to odd and unpredictable behaviour. 

However, if you only use non-branching decoders (e.g. argmax org sample(n:int)), then this limitation actually does not apply. See for instance the key-value storage example at https://lmql.ai#kv. There we actually have global state, to let the LM store values in a dict. This works, as there is only one decoding branch interacting with it.

To allow users to use stateful functions in a general case (i.e. branching), we are investigating versioned and branching data structures, but have not landed on a final design yet. As a workaround, you may implement state also via a local variable, e.g. in a key value storage example, you can declare a dictionary in your prompt code, e.g. `store = {}`, and then only use external functions like `set_value(store: dict, key: str, value: Any)`, that do not rely on global but only local state. Due to the way branching is implemented, local state used in this way, is also supported with branching decoders. 

I hope this helps, let me know if any other questions come up. Feel free to also share your thoughts and ideas on future directions regarding this mechanic.

**Comment by vivien000** [comment]
Hi Luca. Many thanks for this clear and detailed answer. That's great that caching is up to the user. Again, congratulations to you and your co-authors for such an inspiring project!
