### ISSUE TITLE
Question about tokens consumption

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [eth-sri/lmql#131]
Hi there 👋 

Thanks a lot for the amazing project. I read the paper but I thought I can directly ask to be sure. Let's take the example from the README

```python
"Greet LMQL:[GREETINGS]\n" where stops_at(GREETINGS, ".") and not "\n" in GREETINGS

if "Hi there" in GREETINGS:
    "Can you reformulate your greeting in the speech of \
     victorian-era English: [VIC_GREETINGS]\n" where stops_at(VIC_GREETINGS, ".")

"Analyse what part of this response makes it typically victorian:\n"

for i in range(4):
    "-[THOUGHT]\n" where stops_at(THOUGHT, ".")

"To summarize:[SUMMARY]"
```

My fear is that everytime we encounter a `[VARIABLE]` we will resend everything we have before to the LLM thus actually consuming a lot of tokens. 

For instance here we will send 4x the text before `[THOUGHT]`. I realise that the other way, so prompting the model to say "give me 4 thoughts" in reality may require quite a lot more of tokens of your prompt but I was still wondering if you have some good practices and tricks.

Thanks a lot

Fra

**Comment by lbeurerkellner** [comment]
Hi Francesco,

Indeed, since the OpenAI API is quite limited, we do have to issue one request per placeholder variable, thereby incurring a total of 7 requests, each time counting the tokens in the prompt so far. Depending on model behaviour, however, we leverage speculative execution, which allows us to save some of these requests, if the model naturally adheres to our query program. See https://lmql.ai/blog/release-0.0.6.html for more details on this form of caching + speculative execution. LMQL also provides usage statistics on the consumed number of tokens, requests and billed tokens, as discussed in the docs: https://docs.lmql.ai/en/stable/language/openai.html#monitoring-openai-api-use.

Overall, the execution of query programs like the above, therefore can be compared to the cost complexity of the OpenAI Chat API, where you have to pay per message from the model, including the prompt up to that point.

For local models, of course, this limitation does not apply, as we can simply continue generation between placeholder variables, which does not incur additional request costs or latency.

I hope this answers your question.

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks a lot for the detailed question and thanks again for the awesome project!

**Comment by FrancescoSaverioZuppichini** [comment]
> Hi Francesco,
> 
> Indeed, since the OpenAI API is quite limited, we do have to issue one request per placeholder variable, thereby incurring a total of 7 requests, each time counting the tokens in the prompt so far. Depending on model behaviour, however, we leverage speculative execution, which allows us to save some of these requests, if the model naturally adheres to our query program. See https://lmql.ai/blog/release-0.0.6.html for more details on this form of caching + speculative execution. LMQL also provides usage statistics on the consumed number of tokens, requests and billed tokens, as discussed in the docs: https://docs.lmql.ai/en/stable/language/openai.html#monitoring-openai-api-use.
> 
> Overall, the execution of query programs like the above, therefore can be compared to the cost complexity of the OpenAI Chat API, where you have to pay per message from the model, including the prompt up to that point.
> 
> The paper evaluation and initial design of LMQL assumes access to local models, where this limitation does not apply. There we can simply continue generation between placeholder variables, which does not incur additional request costs or latency. Hopefully, in the future, OpenAI APIs will be extended accordingly to allow for similar use of their models.
> 
> I hope this answers your question.

just tried it now, got a 50% reduction in tokens -> may I ask you how this is implemented under the hood?
