### ISSUE TITLE
Versioning consistency

### ISSUE THREAD

**Issue by mludvig** [eth-sri/lmql#142]
Hi, any chance to bring some consistency to the package versioning?

Right now there are 3 different versions:
1. `setup.cfg` says it's "0.0.6.4"
2. the git tag says is "0.7b2"
3. `src/lmql/version.py` says it's "0.999999 (dev)"

It's a little hard to know what version one has actually installed...

**Comment by lbeurerkellner** [comment]
Hi there,

thanks for raising this. With release `0.7` we will move to semantic versioning going right to `0.7` instead of `0.0.7`, with the third digit being reserved for patch releases in the future (see 0.0.6.6 release notes: https://lmql.ai/blog/release-0.0.6.6.html). 

The current 0.7b2 is a pre-release (also marked as such on pypi), which adds major new features. We have not officially announced it yet, as we want to get the documentation up to date first. `0.0.6.6` is the latest full release that matches the current documentation.

`0.999999` is only reported for source distribution, to indicate that you are using a Git-based version, that is likely ahead of everything else installed via `pip`. I just also updated our `setup.cfg` to reflect that for the source distribution. 

I hope that clarifies things. Sorry about the confusion around the semver switch, we should definitely have done this from the beginning on.
