### ISSUE TITLE
[Question] How to enforce the LLM to follow a specific linguistic pattern

### ISSUE THREAD

**Issue by ChezzPlaya** [eth-sri/lmql#172]
I would like to use LMQL in order to generate a test case description from a given utterance that follows a specific linguistic pattern. For example, my LMQL Code would look like as the following:

```
argmax
    Test Case Description: [TEST_CASE_DESCRIPTION]
    
    Preconditions:
      Test Steps:
      - [TEST_STEP]: [VERB] the [OBJECT] to [ARGUMENT] 
 from "meta-llama/Llama-2-13b-hf"
```

Here is especially the Teststep part interesting, because this shall follow a linguistic pattern that is called imperative mood (or imperative verbal phrase). 

The question arises, how can I constraint the underlying LLM to generate verbs, object and an optional argument. Obviously, I can't write a simple `where` clause due to huge amount of words. 

@lbeurerkellner Can I maybe utilize the spacy or nltk module for this task, so I can check e.g. whether the word is a verb? Or can I achieve this behavior maybe in a different (simpler) way?

**Comment by lbeurerkellner** [comment]
This is an interesting challenge. In general, since LMQL does always mask ahead-of-time when it comes to token generation, it is not advisable to check words only after they have been generated e.g. via spacy or nltk. The reason for this is that backtracking when a word does not align with your validation criterion is not feasible (very expensive).

Pre-computing the mask is the way to go here, although I can see why you think this may be unfeasible. However, you have to consider that the model vocabulary is finite (typically 20-50k tokens, 100k max). So to derive token masks you check the entire vocabulary for prefixes of valid words (once), and then apply them during generation. You need to do some manual prefix and continuation checking, but in general this works. To start with, I can recommend you have a look at https://docs.lmql.ai/en/latest/language/custom-constraints.html, which explains the fundamentals of constraining in LMQL. Happy to chat more about this, if you intend to build your own constraint. E.g. we could add support for `verb()` and `object()` constraints.
