### ISSUE TITLE
Would LMQL work with MLC-LLM?

### ISSUE THREAD

**Issue by ChezzPlaya** [eth-sri/lmql#175]
@lbeurerkellner I don't know if you are aware of the following project: https://github.com/mlc-ai/mlc-llm. This thing is crazy fast! Would be great to see LMQL working with this...

**Comment by lbeurerkellner** [comment]
As of now, MLC-LLM does not offer a low-level API which allows us to integrate it easily. Most specifically, LMQL requires support for logit_bias, i.e. a way to shift next-token distributions on each step during decoding. 

I have not yet seen an issue about this over in their repository. If you are interested in LMQL supporting this, I suggest that you first raise it with them, so we can get something going. I am not sure, however, if it aligns with their project goals, as their efforts seems very much focused on providing a great end-user experience rather than offering a general-purpose inference backend.
