### ISSUE TITLE
HF Llama Indexing Issue

### ISSUE THREAD

**Issue by chrispan68** [eth-sri/lmql#28]
I'm currently trying to use the huggingface LlamaForCausalLM. I downloaded the weights, and hosting / inference work great.

The only issue is that there is some tokenization issue going on.  

My .lmql file looks like this: 

`argmax
   """Once upon a time[GENERATION]"""
from 
   "llama/hf_llama7b"
where
   len(GENERATION) < 40`

However, my output is a bit messed up:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/25231523/232655687-0f593a51-9063-43ab-badd-e52a562c0bc1.png">

I think the issue has to do with the llama tokenizer always prepending the \<s\> token (beginning of string) to any text it tokenizes. This creates two failure potential failure modes that could result in the behavior above:

1) it potentially throws off any indexing that somehow doesn't accounts for the \<s\>
2) if lmql tokenizes an any intermediate text, we incorrectly add the \<s\> again. (For the intermediate text tokenizations we should pass add_special_tokens=False)

The issue is that I'm not familiar with the tokenization logic for lmql. If someone gave me a quick high-level rundown of all the relevant tokenization files to change, I can submit a PR.

**Comment by lbeurerkellner** [comment]
Hi Chris, thanks for raising this, I suspect (2) is the issue here.

Can you point me to the resources that allow one to get your version of llama/hf_llama7b. We have the weights (including permission to use them), but I have not found a good way to make easily work with HF yet.

If you want to have a look, I would suggest start looking into https://github.com/eth-sri/lmql/blob/main/src/lmql/runtime/hf_integration.py#L60 first. There, we handle the edge case, that some tokenizer add a bos_token_id, which LMQL does by itself. Maybe this can already be fixed by moving this logic directly to https://github.com/eth-sri/lmql/blob/main/src/lmql/runtime/tokenizer.py.

**Comment by lbeurerkellner** [comment]
Interestingly I can't get a LLamaTokenizer to work on my machine, e.g. this code never finishes executing and depending on environment sometimes tokenizer.bos_token_id spirals into a recursion loop in HF transformers code:

```
import transformers 
tokenizer = transformers.AutoTokenizer.from_pretrained("aleksickx/llama-7b-hf")
print("loaded")
print("bos_token_id")
print(tokenizer.bos_token_id)
```

**Comment by lbeurerkellner** [comment]
`lmql.model.serve.TokenizerProcessor` is outdated and should be removed. I think, the inference server does not really do tokenisation anymore IIRC. At least I yanked out the endpoints for that yesterday.

**Comment by lbeurerkellner** [comment]
The underlying issue of this bug report has been fixed in the latest version, together with our addition of llama.cpp as model inference backend.

If you want to use llama models with HF transformers, I recommend `huggyllama/llama-7b`, which includes the latest fixes to the tokenizer implementations on the HF side. Older Llama models on the hub, sometime still included (slow variant) tokenises with buggy behaviour, that also affected LMQL.
