### ISSUE TITLE
Do any of the playground examples work ?

### ISSUE THREAD

**Issue by younes-io** [eth-sri/lmql#311]
As I had some errors when I use lmql with python, I wanted to test in the official examples in the playground as-is, so I entered my OpenAI API key, but only one example executes.. All the others I tried (at least 6 or 7) actually fail.
Could you please tell me which examples should I rely on to my code ?
Are the docs in the examples up-to-date ? or are they obsolete ?
I would really appreciate your feedback on this.

**Comment by lbeurerkellner** [comment]
Hi there, 

Unfortunatly, because of the shutdown of the openai/text-davinci-… models by OpenAI early this month, the web playground is no longer interactively functional.

Most code samples should work as-is though with a local install and using the newer gpt-3.5-turbo-instruct (if you want to use OpenAI). This newer model is not available in the web playground, because of the unavailability of a suitable tokenizer in a web assembly environment.

I plan to adjust the web playground to inform about that, but probably will keep it alive as a viewer for the preconputed code samples.

**Comment by younes-io** [comment]
Thank you @lbeurerkellner for your feedback

I only have access to `gpt-3.5-turbo`, do you think that would work with the examples? (I tried but I get errors)

**Comment by lbeurerkellner** [comment]
gpt-3.5-turbo is a OpenAI Chat model, which means it can only be used with a limited feature set. See also https://lmql.ai/docs/models/openai.html#chat-api-support.

**Comment by younes-io** [comment]
@lbeurerkellner : Does that mean that LMQL supports only legacy models ? Because as far as I know, if you create a new deployment on Azure OpenAI now, it'll be a chat model; other types of models are legacy now..

**Comment by tfriedel** [comment]
Can the new logprobs feature of ChatGPT models potentially be useful here? 
https://cookbook.openai.com/examples/using_logprobs

**Comment by lbeurerkellner** [comment]
logprobs are an interesting development, but unfortunately not enough to really support OpenAI models right now. See more discussion here https://github.com/eth-sri/lmql/pull/25. 

`gpt-3.5-turbo-instruct` is the recommended OpenAI model right. Chat models remain limited in functionality, due to API restrictions.
