### ISSUE TITLE
Length constraints unexpected behaviour

### ISSUE THREAD

**Issue by JasperDekoninck** [eth-sri/lmql#53]
Consider the following query:

```python
sample(temperature=0.8, openai_chunksize=32, max_len=128, chatty_openai=True)
    "The movie review in positive sentiment is: '[OUTPUT]"
FROM
    "openai/text-ada-001"
WHERE
    len(OUTPUT) == 50
```
This constraint is very specific, but seems to be ignored by LMQL. As a result, I get the following error:
`AssertionError: The decoder returned a sequence that exceeds the provided max_len (max_len=64, sequence length=64). To increase the max_len, please provide a corresponding max_len argument to the decoder function.`

A similar story when we require OUTPUT to be of at least length 50:

```python
sample(temperature=0.8, openai_chunksize=32, max_len=128, chatty_openai=True)
    "The movie review in positive sentiment is: '[OUTPUT]"
FROM
    "openai/text-ada-001"
WHERE
    len(OUTPUT) > 50
```
In this case, LMQL keeps querying the model, despite len(OUTPUT) > 50 already having occurred. At the end, no error occurs because the longer output still satisfies the constraint. Not sure how often this constraint appears in relevant use cases though.

**Comment by lbeurerkellner** [comment]
Thanks, the first example will be fixed by the next release (already on main). 

The second example is expected behavior currently. After OUTPUT has exceeded length 50, LMQL essentially waits for the language model to naturally produce the EOS token, which never happens. As a consequence you'll get the max_len error. I think in this particular case, implementing https://github.com/eth-sri/lmql/issues/52 will help.
