### ISSUE TITLE
How to use GPT2 in local environment?

### ISSUE THREAD

**Issue by Dongximing** [eth-sri/lmql#83]
Hi, need I to load the gpt2 model in local environment and could I use play ground to run the code such as "argmax "Hello[WHO]" from "/Users/ximing/Desktop/gpt2""

**Comment by lbeurerkellner** [comment]
If you want to use GPT 2 in the same process as the LMQL query runs in, you can just specify `local:gpt2` as model in the `from` clause. Otherwise, you can also use `lmql serve-model` to run the model in the background. Make sure to also read the related chapter on the documentation: https://docs.lmql.ai/en/stable/language/models.html#transformers-models.

If you have custom weights to a local model, not available from the HuggingFace Hub, you can indeed also specify an absolute path, similar to how you can instantiate such models in HF with `AutoModel.from_pretrained`.

**Comment by Dongximing** [comment]
Hi, I have tried it, but it still gets error, my code is 

import lmql
from lmql.tests.expr_test_utils import run_all_tests
from transformers import AutoModel
model = AutoModel.from_pretrained('/Users/ximing/Desktop/gpt2-medium')
def test_or():
    @lmql.query
    async def q():
        '''lmql
        argmax
            "a b[OUTPUT]"
        FROM
            "AutoModel.from_pretrained('/Users/ximing/Desktop/gpt')"
        WHERE
            OUTPUT in ['a','b']
        '''
    result = lmql.main(q)[0]
    print(result)

run_all_tests(globals())
could you give me a real example or how to fix it? thanks

**Comment by lbeurerkellner** [comment]
You almost got it. Instead of providing `"AutoModel.from_pretrained('/Users/ximing/Desktop/gpt')"`, just provide the path, i.e. `"/Users/ximing/Desktop/gpt"`. Let me know if that works for you.
